### ISSUE TITLE
Error: x2 is not defined

### ISSUE THREAD

**Issue by Miega** [schartier/angular-farbtastic#6]
Got the following error when trying to set this up.

```
ReferenceError: x2 is not defined
    at Farbtastic.drawCircle (http://localhost:3000/bower_components/angular-farbtastic/angular-farbtastic.js:148:24)
    at Farbtastic.initWidget (http://localhost:3000/bower_components/angular-farbtastic/angular-farbtastic.js:120:14)
    at new Farbtastic (http://localhost:3000/bower_components/angular-farbtastic/angular-farbtastic.js:21:14)
    at ngModel.$render (http://localhost:3000/bower_components/angular-farbtastic/angular-farbtastic.js:463:54)
    at ngModelWatch (http://localhost:3000/bower_components/angular/angular.js:26472:14)
    at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1968:35)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:16655:34)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016:23)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:16928:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2079:22)
```

x2 refers to a variable that controls the segment endpoints for the hue circle.

**Comment by Miega** [comment]
Found the error on line 147. A misplaced semicolon was causing the error.
